# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2e022705a3766b1cb2e7128c2a6717cf8626b0abe9fa55c17c069d40baa2a76e85eb26739fd676b9dd591d9d0ffffd47fb8b2e6412f208f46d552d87e662acf

test:
  secret_key_base: 0d4f950649bf7fb6acebe5f21d2c10dd1641d5284d8c85932e0a385ffa26fa11bb784a6bba6e98197f70751f4fa63a3f6379cc149f2694462271ab41c21075f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
